### ISSUE TITLE
struct.decode is returning "undefined"

### ISSUE THREAD

**Issue by sdcaulley** [callmehiphop/pb-util#7] opened 2020-05-08 18:16 UTC
Hello.  I am trying to use the struct.decode method.  My code is structured like this:
```js
const data = {
  "fields": {
    "Hello": {
      "kind": "stringValue",
      "stringValue": "Deep 6"
    }
  }
};

const transData = struct.decode(data);
```

And what I am getting is : 
`{ Hello: undefined } `

Am I doing something wrong?

**Comment by callmehiphop** [comment] 2020-05-12 23:34
Hi @sdcaulley, I went ahead and wrote a unit test using the provided example and it seems to be passing. Can you verify that you're using the latest release? If so, is there any more info you might be able to provide to help me reproduce?

**Comment by callmehiphop** [comment] 2020-05-19 20:44
Going to close this out, if your issue continues to persist please let me know and I'll happily re-open.

**Closed as completed by callmehiphop** 2020-05-19 20:44 UTC
Labels: question
